name: Test Pipeline and Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python test_script.py
    
    - name: Start Streamlit app with ngrok and capture URL
      run: |
        # Start Streamlit app in the background
        nohup streamlit run dashboard.py &

        # Install ngrok if it's not installed
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc
        echo "deb https://ngrok-agent.s3.amazonaws.com/deb stable main" | sudo tee /etc/apt/sources.list.d/ngrok-stable.list
        sudo apt-get update
        sudo apt-get install ngrok

        # Start ngrok and capture the public URL
        ngrok http 8501 &

        # Wait for the tunnel to be established and extract the public URL
        sleep 10  # Adjust sleep time if needed
        PUBLIC_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url)
        echo "Public URL: $PUBLIC_URL"
        echo "::set-output name=dashboard_url::$PUBLIC_URL"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.json
        retention-days: 90
