name: Test Pipeline and Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python test_script.py
    
    - name: Start Streamlit Dashboard with ngrok
      id: start_dashboard
      run: |
        # Start the Streamlit app with ngrok and capture the output (URL)
        public_url=$(python run_app.py)
        echo "Public URL: $public_url"
        # Set the output so it can be accessed by later steps
        echo "::set-output name=dashboard_url::$public_url"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.json
        retention-days: 90
    
    - name: Display public URL for Dashboard
      run: |
        echo "Dashboard is accessible at: ${{ steps.start_dashboard.outputs.dashboard_url }}"
