name: Test Pipeline and Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python test_script.py
    
    - name: Start Streamlit app with ngrok and capture URL
      run: |
        # Start Streamlit app in the background
        nohup streamlit run dashboard.py &

        # Download and install ngrok directly
        curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        sudo mv ngrok /usr/local/bin/ngrok

        # Create the ngrok2 directory if it doesn't exist
        mkdir -p ~/.ngrok2

        # Set ngrok authentication token
        echo "authtoken: 2qpRWeIX1oVNuMoOacmRWFXqyXQ_2ZDQHJLZK5FyB8iXJpe23" > ~/.ngrok2/ngrok.yml

        # Start ngrok and capture the public URL
        ngrok http 8501 &

        # Wait for the tunnel to be established and extract the public URL
        sleep 10  # Adjust sleep time if needed
        PUBLIC_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url)
        echo "Public URL: $PUBLIC_URL"
        
        # Set the dashboard URL as an environment variable to be used in later steps
        echo "DASHBOARD_URL=$PUBLIC_URL" >> $GITHUB_ENV
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.json
        retention-days: 90
