name: Deploy Streamlit App with Ngrok

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y unzip curl jq

    - name: Install ngrok
      run: |
        curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        sudo mv ngrok /usr/local/bin/ngrok

    - name: Authenticate ngrok with authtoken
      run: |
        ngrok authtoken 2qpRWeIX1oVNuMoOacmRWFXqyXQ_2ZDQHJLZK5FyB8iXJpe23

    - name: Start Streamlit app
      run: |
        nohup streamlit run dashboard.py &

    - name: Start ngrok and get public URL
      run: |
        ngrok http 8501 &
        sleep 10
        PUBLIC_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url)
        echo "Public URL: $PUBLIC_URL"
        echo "DASHBOARD_URL=$PUBLIC_URL" >> $GITHUB_ENV

    - name: Upload public URL as an artifact
      run: echo "DASHBOARD_URL=$PUBLIC_URL" >> $GITHUB_ENV
