name: Test Pipeline and Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python test_script.py
    
    - name: Start Streamlit Dashboard with ngrok
      run: |
        python run_app.py &
        sleep 5  # Allow some time for ngrok to establish the tunnel
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.json
        retention-days: 90
    
    - name: Display public URL for Dashboard
      run: |
        curl -s http://127.0.0.1:5000/  # Test if the server is accessible (replace with actual ngrok URL if needed)
        echo "Dashboard is accessible at: $(curl -s http://127.0.0.1:5000/)"
